### PR TITLE
Converted to UFR format

### PR DESCRIPTION
**Pull request by aaronbell**
I'm helping update repositories to Google's [United Font Repro](https://github.com/googlefonts/Unified-Font-Repository) format, as well as correcting STAT table issues in variable fonts. As an added benefit to this process, the font will now build automatically when PRs are accepted. 

Additionally:
- I added a preprocessing step that eliminates the need for you to manually run the Glyphs script to produce a "ship ready" version.
- Both Signika normal and Negative are building from the standard Signika.glyphs file. There are two additional instances added to the font at either end of the designspace in the glyphs file, but otherwise no additional work necessary for you. 
- The only thing is that this script does not automatically generate the SC versions. If that's an issue, it shouldn't be too bad to build that into the build script. 

Once merged in, we'll submit an update to Google Fonts. Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by aaronbell** [comment]
@Ancymonic Following up. Are you still maintaining this repro?

**Comment by Ancymonic** [comment]
@aaronbell Hi Aaron, sorry I am taking some time off from work and I have missed your fork request. I have some uncommited changes, so I need to figure out how not to loose them.

**Comment by aaronbell** [comment]
No problem. What are the nature of your changes? Just glyph modifications? If you upload them to your repro I can do the merge with my version.

**Comment by Ancymonic** [comment]
Just some kerning corrections. I will have a look on Monday when I am be back by the computer. But merge on your side sounds good.

**Comment by aaronbell** [comment]
@Ancymonic Just thought I'd check in :)

**Comment by Ancymonic** [comment]
@aaronbell No worries, I am working on it. But I need a bit more time to figure out what the changes were. I am traveling and unfortunatelly I dont have access to all my files.

**Comment by aaronbell** [comment]
No problem. Take your time.

**Comment by Ancymonic** [comment]
@aaronbell I have just pushed the latest version. Only some kerning and spacing issues were fixed. The files are all yours!

**Comment by aaronbell** [comment]
Hi @Ancymonic, I've pushed an update into the repro that merges in your update. You'll have to resolve the conflict (sorry!), but you can just accept it.

**Comment by aaronbell** [comment]
I should note, BTW, that this PR is currently set per Google's specs wherein the  NEGA axis has been removed from the standard version. Once that requirement changes, it will be fairly easy to swap to that version.

**Comment by Ancymonic** [comment]
@aaronbell I have not been able to easily merge the conflicting changes. Please, get my source file from the commit `930d748a656a7a7365ccf8f0453acfe2eef84ecb` and merge/reproduce your changes again. Thank you!

**Comment by aaronbell** [comment]
@Ancymonic I rebased the PRs and got the conflicts sorted :)

**Comment by Ancymonic** [comment]
@aaronbell I think something went wrong. The Signika.glyphs file in your commit has just 62 glyphs, the original source file should have 1417 glyphs.

**Comment by aaronbell** [comment]
@Ancymonic I'm not seeing that. Both the version on my fork and in the main repro (I downloaded it fresh) have the full complement of glyphs. Are you sure you're looking at the right glyphs file?

**Comment by Ancymonic** [comment]
@aaronbell Ok, that was some Sourcetree bug. Had to clone the repo again. All good now 🙂 Thank you!

**Pull request merged**
